version: '3.8'
services:                     
    mongodb:
        image: mongo:5.0
        container_name: cosc404-lab7-mongodb
        ports:
        - 27017:27017
        volumes:
        - mongodb:/data/db
        environment:
        - MONGO_INITDB_ROOT_USERNAME=lab7
        - MONGO_INITDB_ROOT_PASSWORD=404mgbpw
volumes:     
    mongodb:    
